### PR TITLE
Lab3

### PR DESCRIPTION
**Pull request by jc-yap**
@thornd3 I'll finish it tomorrow

### CODE REVIEW

**Comment by jc-yap** [comment]
Just finished the draft

**Comment by thornd3** [comment]
Your lab is awesome as always. Just a few things
For problem 2 you could go into a little more detail about the relationship between Gaussian and Rayleigh distributions and why our distribution is a Rayleigh. 
You could also go into a little more detail into the relationship between the mean and RMS of our data- it seemed like a bit of an unexplained jump from knowing the mean to our RMS being the standard deviation.

**Comment by thornd3** [comment]
Additionally, for problem #3 you could go into why we have a Poisson distribution- what qualities of our data lead towards that. 
Your comparison with a Gaussian and you convolved Poisson is fantastic and really in depth though. Nice job.

**Comment by jc-yap** [comment]
@oliviatessa  11 hours

**Comment by oliviatessa** [comment]
Hi Josh, 

Here are my comments on your lab 3: 

P.1 
- There are other ways to get rid of bad data close to the mean of the distribution (plotting along a different axis or using other dimensions of the metadata). These are either beyond the scope of the class or not provided in the problem, but these methods are interesting to explore a little further. 

P.2 
- Great job with this problem! 

P.3 
- I like your exploration of the CLT at the end of the lab. The Gaussian is a really good approximation to the Poisson distribution at lambdas above 20, so it isn't surprising that the sigma calculated from the Gaussian is so close to the one calculated from the Poisson. 

Great work! 

Best, 
Olivia

**Pull request closed without merging**
