### PR TITLE
Lab1

### PR DESCRIPTION
**Pull request by jc-yap**
@thornd3 maybe this works now

### CODE REVIEW

**Comment by thornd3** [comment]
Your shit is fire my dude
quick notes: Your vertical scale on your histogram before line 43 seems off, and it doesn't seem to match the Chi squared line plot above.

**Comment by jc-yap** [comment]
Thanks. That histogram was meant to represent the distribution of outcomes for 100,000 experiments. I have a normalized plot of it below that matches the chi-squared plot.

**Comment by jc-yap** [comment]
@oliviatessa

**Comment by oliviatessa** [comment]
Awesome job, Josh! 

Only note is that you should explain the differences between the different types of z-score tables. Why did you choose the one you did?

**Pull request closed without merging**
