### PR TITLE
Lab2

### PR DESCRIPTION
**Pull request by jc-yap**
@thornd3 What I have so far

### CODE REVIEW

**Comment by jc-yap** [comment]
I just pushed an updated .mlx file and html file to the branch, you might be able to see them but let me know if you don't.

**Comment by thornd3** [comment]
I believe I can. I remember for version 2 in Problem 3 at the end of the lab I asked and she mentioned we had to convolute it 10k times. I think blowing it up by a value of 10k would make the information you get from it irrelevant, it's the same distribution x10k. I think this makes sense- you would have the same distribution but with a much larger mean, which makes sense because you would expect to see those brighter pixels more often as you survey more pixels.

**Comment by thornd3** [comment]
that would also allow you to calculate sigma and significance. or should you take convolutions and then then the mean? to get a normalized distribution? I'm not quite sure myself, but you may want to double check.

**Comment by jc-yap** [comment]
@oliviatessa

**Comment by oliviatessa** [comment]
Hi Josh, 

Here are my comments for your lab 2: 
P.1 
- I think choosing something other than stairs would make these plots more visually understandable. Yes, this is sort of nit-picky, but the figures are one of the most important parts of a scientific paper/memo. Try playing around with different plot styling to make your plots more clear. 
- I think you could go further in making your plots more self-contained by adding captions. Remember, you can repeat what you say about the plot in the main text and just make it more concise. 
- You could plot a log scale Gaussian along with your 1 and 5 day Poisson distributions to show that the distribution approaches Gaussian 
- I'm a little confused by your hypothetical example. Specifically your log plot with the marker - can you make what you are going for here any clearer? 

P.2 
- I like that you compared your Rayleigh to a Gaussian on the same plot. I wrote the above before I saw this part. 
- The Gaussian and convolved Rayleigh lie on top of each other for a narrow range of x-values. How many convolutions would it take for it to completely look like the Gaussian? 

P.3 
- I'm a little confused why you didn't approach finding sigma for you 10k trial distribution the same way you found sigma for your single trial. 

P.4 
- Why do you think sigma is not applicable to the 10k trial version? 
- I really like your plot comparing the two log Gaussians 
- Also great way to visualize how the detection threshold changes 

In general, try making captions for you plots. Also, adding sections for each problem would make your report more readable. 

Best, 
Olivia

**Pull request closed without merging**
